#!/usr/bin/env python3
# /// script
# requires-python = ">=3.9"
# dependencies = ["scikit-robot>=0.3.39", "pycollada"]
# ///
"""Generate a K_ARM_DUALARM URDF whose arm links use primitive shapes.

The arm meshes cannot be redistributed, so every arm link is replaced by a
box / cylinder / sphere fitted with scikit-robot. Links whose name matches
``--keep-pattern`` (the harvest gripper by default) keep their original
meshes.

Run it with uv from the package directory; ``package://`` mesh paths are
resolved through ``ROS_PACKAGE_PATH``::

    ROS_PACKAGE_PATH=$(dirname $PWD) uv run scripts/generate_primitive_urdf.py
"""

import argparse
import copy
from pathlib import Path
import re
import tempfile

from lxml import etree
from skrobot.urdf import convert_meshes_to_primitives


PACKAGE_DIR = Path(__file__).resolve().parent.parent


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--input', type=Path,
                        default=PACKAGE_DIR / 'urdf' / 'K_ARM_DUALARM.urdf',
                        help='URDF that references the original meshes.')
    parser.add_argument('--output', type=Path,
                        default=PACKAGE_DIR / 'urdf' / 'K_ARM_DUALARM_primitive.urdf')
    parser.add_argument('--keep-pattern', default=r'(gripper|finger)',
                        help='Regex of link names whose meshes are kept as is.')
    return parser.parse_args()


def main():
    args = parse_args()
    keep = re.compile(args.keep_pattern)

    with tempfile.TemporaryDirectory() as tmp:
        converted_path = Path(tmp) / 'converted.urdf'
        count = convert_meshes_to_primitives(args.input, output_file=converted_path)
        print('scikit-robot converted {} geometry elements'.format(count))

        original = etree.parse(str(args.input))
        converted = etree.parse(str(converted_path))

    original_links = {link.get('name'): link
                      for link in original.getroot().findall('link')}
    restored = []
    for link in converted.getroot().findall('link'):
        name = link.get('name')
        if keep.search(name):
            link.getparent().replace(link, copy.deepcopy(original_links[name]))
            restored.append(name)
    print('kept original meshes for: {}'.format(', '.join(restored)))

    remaining = [mesh.get('filename')
                 for link in converted.getroot().findall('link')
                 if not keep.search(link.get('name'))
                 for mesh in link.iter('mesh')]
    if remaining:
        raise RuntimeError('arm links still reference meshes: {}'.format(remaining))

    comment = etree.Comment(
        ' Generated by k_arm_descriptions/scripts/generate_primitive_urdf.py from {}.'
        ' Arm links are scikit-robot primitives; do not edit by hand. '.format(args.input.name))
    converted.getroot().insert(0, comment)
    converted.write(str(args.output), xml_declaration=True, encoding='utf-8')
    print('wrote {}'.format(args.output))


if __name__ == '__main__':
    main()
